name: Analyze branch

on:
  push:
    branches:
      - main
      - new_branch
  pull_request:
    branches:
      - new_branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: 'Run an analysis of the main branch'
        uses: ptuc/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ENDPOINT: 'sonar.wks-recette.com'
          args: >
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
            -Dsonar.pullrequest.base=${{ github.BASE_REF }}
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.scm.provider=git
            -Dsonar.sources=src
            -Dsonar.projectKey=mariuspop86_potential-palm-tree
